name: pocket2mol_rl
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=0.15.0
  - aiosignal=1.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.1
  - backcall=0.2.0
  - biopython=1.79
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.12.12
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cmake=3.19.6
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - easydict=1.9
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - ffmpeg=4.3
  - fontconfig=2.14.0
  - freetype=2.10.4
  - frozenlist=1.2.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth-oauthlib=0.4.1
  - greenlet=1.1.2
  - grpcio=1.42.0
  - icu=67.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - ipykernel=6.13.0
  - ipython=8.3.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.2
  - krb5=1.19.4
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.84.0
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.0.10
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.40.0
  - libxcb=1.13
  - lmdb=0.9.29
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - oauthlib=3.2.0
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1w
  - packaging=21.3
  - pandas=1.4.2
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - pixman=0.38.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycairo=1.21.0
  - pycparser=2.21
  - pyg=2.0.4
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-lmdb=1.2.1
  - python-louvain=0.16
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-cluster=1.6.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.13
  - pytorch-spline-conv=1.2.1
  - pytz=2021.3
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - rdkit=2022.03.2
  - readline=8.1.2
  - reportlab=3.5.68
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rhash=1.4.1
  - rsa=4.7.2
  - six=1.16.0
  - sqlalchemy=1.4.36
  - sqlite=3.38.3
  - stack_data=0.2.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.11
  - torchvision=0.11.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
      - aiohttp==3.8.6
      - aiohttp-cors==0.7.0
      - aiohttp-retry==2.8.3
      - aiorwlock==1.3.0
      - alabaster==0.7.13
      - alembic==1.12.0
      - anyio==3.7.1
      - attrs==23.1.0
      - babel==2.12.1
      - backoff==2.2.1
      - blessed==1.20.0
      - blinker==1.7.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - cmaes==0.10.0
      - colorful==0.5.5
      - colorlog==6.7.0
      - comm==0.1.4
      - cssselect==1.2.0
      - cssutils==2.7.1
      - databricks-cli==0.18.0
      - datasets==2.14.4
      - deprecated==1.2.14
      - dill==0.3.7
      - distlib==0.3.7
      - dm-tree==0.1.8
      - docker==6.1.3
      - docutils==0.18.1
      - einops==0.6.1
      - evaluate==0.4.0
      - exceptiongroup==1.1.3
      - farama-notifications==0.0.4
      - fastapi==0.104.1
      - filelock==3.12.2
      - flask==3.0.0
      - fsspec==2023.6.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-api-core==2.14.0
      - google-auth==2.23.4
      - googleapis-common-protos==1.61.0
      - googledrivedownloader==0.4
      - gpustat==1.1.1
      - gputil==1.4.0
      - gunicorn==21.2.0
      - gymnasium==0.28.1
      - gymnasium-notices==0.0.1
      - h11==0.14.0
      - h5py==3.9.0
      - httpcore==0.18.0
      - httptools==0.6.1
      - httpx==0.25.0
      - huggingface-hub==0.16.4
      - imageio==2.31.1
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - ipywidgets==8.1.0
      - isodate==0.6.1
      - itsdangerous==2.1.2
      - jaraco-classes==3.3.0
      - jax-jumpy==1.0.0
      - jeepney==0.8.0
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyterlab-widgets==3.0.8
      - keyring==24.2.0
      - knockknock==0.1.8.1
      - lazy-loader==0.3
      - lxml==4.9.3
      - lz4==4.3.2
      - mako==1.2.4
      - markdown-it-py==3.0.0
      - matrix-client==0.4.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - meeko==0.3.0
      - mlflow==2.8.0
      - more-itertools==10.1.0
      - msgpack==1.0.5
      - multiprocess==0.70.15
      - myst-parser==2.0.0
      - networkx==2.8
      - nvidia-ml-py==12.535.133
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-grpc==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - optuna==3.3.0
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.11.0
      - premailer==3.10.0
      - prometheus-client==0.18.0
      - protobuf==4.25.0
      - py-spy==0.3.14
      - pyarrow==12.0.1
      - pydantic==1.10.13
      - pygments==2.16.1
      - python-dotenv==1.0.0
      - python-telegram-bot==20.6
      - pywavelets==1.4.1
      - querystring-parser==1.2.4
      - ray==2.8.0
      - ray-cpp==2.8.0
      - rdflib==6.1.1
      - referencing==0.30.2
      - regex==2023.8.8
      - responses==0.18.0
      - rich==13.5.2
      - rpds-py==0.9.2
      - safetensors==0.3.2
      - scikit-image==0.21.0
      - scikit-learn==1.1.0
      - scipy==1.8.0
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - setuptools==59.5.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - sqlparse==0.4.4
      - starlette==0.27.0
      - tabulate==0.9.0
      - tensorboardx==2.6.2
      - threadpoolctl==3.1.0
      - tifffile==2023.7.10
      - tokenizers==0.13.3
      - transformers==4.31.0
      - twilio==8.9.1
      - typer==0.9.0
      - typing-extensions==4.8.0
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - vina==1.2.5
      - virtualenv==20.21.0
      - watchfiles==0.21.0
      - websocket-client==1.6.4
      - websockets==12.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.8
      - wrapt==1.16.0
      - xxhash==3.3.0
      - yagmail==0.15.293
      - git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3@9d37a13bf0461427ae0c883db0cd239cef5c750c